################################################################################
#Proyecto          => SAFRE VIVIENDA                                           #
#Propietario       => E.F.P.                                                   #
--------------------------------------------------------------------------------
#Modulo            => CBD                                                      #
#Programa          => CBDP12                                                   #
#Objetivo          => Archivo de definicion de datos globales                  #
#Fecha inicio      => 10/06/2014                                               #
################################################################################

GLOBALS
   #Constantes del proceso de integracion
   CONSTANT ESTADO_ARCHIVO_INTEGRADO    SMALLINT = 2
   CONSTANT ESTADO_ARCHIVO_ERROR        SMALLINT = 3

END GLOBALS