####################################################################
#Modulo            =>CTA                                           #
#Programa          =>CTAP10.inc                                    #
#Objetivo          =>Archivo de definicion de datos                #
#Fecha inicio      =>17 ENERO 2013                                 #
####################################################################

GLOBALS

   CONSTANT INTERVALOS           INTEGER = 10
   
END GLOBALS