####################################################################
#Modulo            =>CTA                                           #
#Programa          =>CTAP07.inc                                    #
#Objetivo          =>Archivo de definicion de datos                #
#Fecha inicio      =>30 SEPTIEMBRE 2013                            #
####################################################################

GLOBALS

   CONSTANT INTERVALOS           INTEGER = 10
   
   CONSTANT PARTE_1              INTEGER = 1
   CONSTANT PARTE_2              INTEGER = 2
   CONSTANT PARTE_3              INTEGER = 3
   CONSTANT PARTE_4              INTEGER = 4
   CONSTANT PARTE_5              INTEGER = 5
   CONSTANT PARTE_6              INTEGER = 6
   CONSTANT PARTE_7              INTEGER = 7
   CONSTANT PARTE_8              INTEGER = 8
   CONSTANT PARTE_9              INTEGER = 9
   CONSTANT PARTE_10             INTEGER = 10
   
END GLOBALS