####################################################################
#Modulo            => NOT                                          #
#Programa          => NOTP02                                       #
#Objetivo          => Archivo de definicion de datos               #
#Fecha inicio      => 04-FEBRERO-2015                              #
####################################################################

GLOBALS

   CONSTANT SMS                      SMALLINT = 1
   CONSTANT CORREO                   SMALLINT = 2

END GLOBALS