####################################################################
#Modulo            =>NOT                                           #
#Programa          =>NOTWS02.inc                                   #
#Objetivo          =>Archivo de variables globales                 #
#Fecha inicio      =>01 JUNIO 2015                                 #
####################################################################

GLOBALS
   CONSTANT NSS_CON_ACLARACION            CHAR(3) = '000'
   CONSTANT NSS_SIN_ACLARACION            CHAR(3) = '001'
   CONSTANT NSS_NO_ENCONTRADO             CHAR(3) = '002'
END GLOBALS