--==============================================================================
-- Version: 1.0.0
-- Fecha ultima modificacion: 11/11/2015
--==============================================================================

################################################################################
#Modulo       => PRT                                                           #
#Programa     => PRTWS11.inc                                                   #
#Objetivo     => Archivo de variables y constantes globales                    #
#Fecha inicio => 11 Nobiembre 2015                                             #
################################################################################

GLOBALS

CONSTANT C_DIAS_ACLARACION_MARCADO SMALLINT = 60
CONSTANT C_HORAS_ACLARACION_REC    STRING = "3 00:00:00" # 72 horas

CONSTANT C_TIPO_ACL_INF SMALLINT = 2
CONSTANT C_TIPO_ACL_FOV SMALLINT = 1
CONSTANT C_TIPO_ACL_SIN SMALLINT = 3

CONSTANT C_ORIGEN_ACL_CED SMALLINT = 1
CONSTANT C_ORIGEN_ACL_REC SMALLINT = 2

CONSTANT C_ESTADO_ACL_PROCEDENTE    SMALLINT = 1
CONSTANT C_ESTADO_ACL_NO_PROCEDENTE SMALLINT = 2

CONSTANT C_DIAGNOSTICO_ACL_1  SMALLINT = 1
CONSTANT C_DIAGNOSTICO_ACL_2  SMALLINT = 2
CONSTANT C_DIAGNOSTICO_ACL_3  SMALLINT = 3
CONSTANT C_DIAGNOSTICO_ACL_4  SMALLINT = 4
CONSTANT C_DIAGNOSTICO_ACL_5  SMALLINT = 5
CONSTANT C_DIAGNOSTICO_ACL_6  SMALLINT = 6
CONSTANT C_DIAGNOSTICO_ACL_7  SMALLINT = 7
CONSTANT C_DIAGNOSTICO_ACL_8  SMALLINT = 8
CONSTANT C_DIAGNOSTICO_ACL_9  SMALLINT = 9
CONSTANT C_DIAGNOSTICO_ACL_10 SMALLINT = 10
CONSTANT C_DIAGNOSTICO_ACL_11 SMALLINT = 11
CONSTANT C_DIAGNOSTICO_ACL_12 SMALLINT = 12
CONSTANT C_DIAGNOSTICO_ACL_13 SMALLINT = 13
CONSTANT C_DIAGNOSTICO_ACL_14 SMALLINT = 14
CONSTANT C_DIAGNOSTICO_ACL_15 SMALLINT = 15

END GLOBALS