#-------------------------------------------------------------------------------
# File: untitled-3.4gl
# GENERATED BY fglwsdl 141859
#-------------------------------------------------------------------------------
# THIS FILE WAS GENERATED. DO NOT MODIFY.
#-------------------------------------------------------------------------------


IMPORT FGL WSHelper
IMPORT com
IMPORT xml


GLOBALS "untitled-3.inc"



#-------------------------------------------------------------------------------
# Service: CancelacionSolicitudPortabilidadService
# Port:    CancelacionSolicitudPortabilidadServicePortType
# Server:  http://172.16.16.204:6141/ws/r/cancelacionSolicitudPortabilidad
#-------------------------------------------------------------------------------

PRIVATE DEFINE cancelacionSolicitudPortabilidadHTTPReq     com.HTTPRequest
PRIVATE DEFINE cancelacionSolicitudPortabilidadHTTPResp    com.HTTPResponse

#-------------------------------------------------------------------------------

#
# Operation: cancelacionSolicitudPortabilidad
#
#
# FUNCTION: cancelacionSolicitudPortabilidad_g
#   RETURNING: soapStatus
#   INPUT: GLOBAL cancelacionSolicitudPortabilidad
#   OUTPUT: GLOBAL solicitudCancelacionPortabilidadResponse
#
FUNCTION cancelacionSolicitudPortabilidad_g()
  DEFINE wsstatus   INTEGER
  DEFINE retryAuth  INTEGER
  DEFINE retryProxy INTEGER
  DEFINE retry      INTEGER
  DEFINE nb         INTEGER
  DEFINE uri        STRING
  DEFINE setcookie  STRING
  DEFINE mustUnderstand INTEGER
  DEFINE request    com.HTTPRequest
  DEFINE response   com.HTTPResponse
  DEFINE writer     xml.StaxWriter
  DEFINE reader     xml.StaxReader

  #
  # INIT VARIABLES
  #
  LET wsstatus = -1
  LET retryAuth = FALSE
  LET retryProxy = FALSE
  LET retry = TRUE
  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")

  IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri IS NULL THEN
    LET CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri = "http://172.16.16.204:6141/ws/r/cancelacionSolicitudPortabilidad"
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET request = com.HTTPRequest.Create(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri)
    CALL request.setMethod("POST")
    CALL request.setCharset("UTF-8")
    CALL request.setHeader("SOAPAction","\"\"")
    CALL WSHelper_SetRequestHeaders(request, CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Request.Headers)
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Version IS NOT NULL THEN
      CALL request.setVersion(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Version)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL request.setHeader("Cookie",CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Cookie)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL request.setConnectionTimeout(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ConnectionTimeout)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL request.setTimeout(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL request.setHeader("Content-Encoding",CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.CompressRequest)
    END IF
    CALL request.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = STATUS
    CALL WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    RETURN wsstatus
  END TRY

  # START LOOP
  WHILE retry
    LET retry = FALSE

    #
    # Stax request
    #
    TRY
      LET writer = request.beginXmlRequest()
      CALL WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(cancelacionSolicitudPortabilidad,writer)
      CALL WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL request.endXmlRequest(writer)
    CATCH
      LET wsstatus = STATUS
      CALL WSHelper_FillSOAP11WSError("Client",SQLCA.SQLERRM)
      RETURN wsstatus
    END TRY

    #
    # PROCESS RESPONSE
    #
    TRY
      LET response = request.getResponse()

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = response.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Cookie = WSHelper_ExtractServerCookie(setcookie,CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper_SetResponseHeaders(response, CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Response.Headers)
      CASE response.getStatusCode()

        WHEN 500 # SOAP Fault
          #
          # STAX SOAP FAULT
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL reader.nextSibling() # Skip SOAP headers
            END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11StartFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
            #
            # STAX SOAP FAULT DESERIALIZE
            #
            CALL reader.nextSibling() # Skip SOAP detail
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)

        WHEN 200 # SOAP Result
          #
          # STAX SOAP RESPONSE
          #
          LET reader = response.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            LET nb = 0
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              IF nb != 0 THEN
                CALL WSHelper_FillSOAP11WSError("Client","One or more headers are missing")
                EXIT CASE
              ELSE
                CALL reader.nextTag()
              END IF
            END IF
          ELSE
           IF reader.isEmptyElement() THEN
             CALL reader.nextTag()
           END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          # Retrieve SOAP Message taking soap:root attribute into account
          IF NOT WSHelper_RetrieveStaxSOAP11Message(reader) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE DESERIALIZE
          #
          CALL xml.Serializer.StaxToVariable(reader,solicitudCancelacionPortabilidadResponse)
          IF NOT WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL response.endXmlResponse(reader)
          LET wsstatus = 0

        WHEN 401 # HTTP Authentication
          IF retryAuth THEN
            CALL WSHelper_FillSOAP11WSError("Server","HTTP Error 401 ("||response.getStatusDescription()||")")
          ELSE
            LET retryAuth = TRUE
            LET retry = TRUE
          END IF

        WHEN 407 # Proxy Authentication
          IF retryProxy THEN
            CALL WSHelper_FillSOAP11WSError("Server","HTTP Error 407 ("||response.getStatusDescription()||")")
          ELSE
            LET retryProxy = TRUE
            LET retry = TRUE
          END IF

        OTHERWISE
          CALL WSHelper_FillSOAP11WSError("Server","HTTP Error "||response.getStatusCode()||" ("||response.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP11WSError("Server",SQLCA.SQLERRM)
      RETURN wsstatus
    END TRY

  # END LOOP
  END WHILE

  RETURN wsstatus

END FUNCTION


FUNCTION cancelacionSolicitudPortabilidadRequest_g()
  DEFINE wsstatus   INTEGER
  DEFINE writer     xml.StaxWriter

  #
  # CHECK PREVIOUS CALL  
  #
  IF cancelacionSolicitudPortabilidadHTTPReq IS NOT NULL AND cancelacionSolicitudPortabilidadHTTPResp IS NULL THEN
    # Request was sent but there was no response yet
    CALL WSHelper_FillSOAP11WSError("Client","Cannot issue a new request until previous response was received")
    RETURN -2 # waiting for the response
  ELSE
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri IS NULL THEN
      LET CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri = "http://172.16.16.204:6141/ws/r/cancelacionSolicitudPortabilidad"
    END IF
  END IF

  #
  # CREATE REQUEST
  #
  TRY
    LET cancelacionSolicitudPortabilidadHTTPReq = com.HTTPRequest.Create(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri)
    CALL cancelacionSolicitudPortabilidadHTTPReq.setMethod("POST")
    CALL cancelacionSolicitudPortabilidadHTTPReq.setCharset("UTF-8")
    CALL cancelacionSolicitudPortabilidadHTTPReq.setHeader("SOAPAction","\"\"")
    CALL WSHelper_SetRequestHeaders(cancelacionSolicitudPortabilidadHTTPReq, CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Request.Headers)
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Version IS NOT NULL THEN
      CALL cancelacionSolicitudPortabilidadHTTPReq.setVersion(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Version)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Cookie IS NOT NULL THEN
      CALL cancelacionSolicitudPortabilidadHTTPReq.setHeader("Cookie",CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Cookie)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ConnectionTimeout <> 0 THEN
      CALL cancelacionSolicitudPortabilidadHTTPReq.setConnectionTimeout(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ConnectionTimeout)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ReadWriteTimeout <> 0 THEN
      CALL cancelacionSolicitudPortabilidadHTTPReq.setTimeout(CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.ReadWriteTimeout)
    END IF
    IF CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.CompressRequest IS NOT NULL THEN
      CALL cancelacionSolicitudPortabilidadHTTPReq.setHeader("Content-Encoding",CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.CompressRequest)
    END IF
    CALL cancelacionSolicitudPortabilidadHTTPReq.setHeader("Accept-Encoding","gzip, deflate")
  CATCH
    LET wsstatus = STATUS
    CALL WSHelper_FillSOAP11WSError("Client","Cannot create HTTPRequest")
    LET cancelacionSolicitudPortabilidadHTTPReq = NULL
    RETURN wsstatus
  END TRY

    #
    # Stax request
    #
    TRY
      LET writer = cancelacionSolicitudPortabilidadHTTPReq.beginXmlRequest()
      CALL WSHelper_WriteStaxSOAP11StartEnvelope(writer)
      CALL WSHelper_WriteStaxSOAP11StartBody(writer)
      #
      # STAX SOAP REQUEST SERIALIZE
      #
      CALL xml.Serializer.VariableToStax(cancelacionSolicitudPortabilidad,writer)
      CALL WSHelper_WriteStaxSOAP11EndBody(writer)
      CALL WSHelper_WriteStaxSOAP11EndEnvelope(writer)
      CALL cancelacionSolicitudPortabilidadHTTPReq.endXmlRequest(writer)
    CATCH
      LET wsstatus = STATUS
      CALL WSHelper_FillSOAP11WSError("Client",SQLCA.SQLERRM)
      LET cancelacionSolicitudPortabilidadHTTPReq = NULL
      RETURN wsstatus
    END TRY

  #
  # PROCESS RESPONSE
  #
  TRY
    LET cancelacionSolicitudPortabilidadHTTPResp = cancelacionSolicitudPortabilidadHTTPReq.getAsyncResponse()
    RETURN 0 # SUCCESS
  CATCH
    LET wsstatus = STATUS
    CALL WSHelper_FillSOAP11WSError("Server",SQLCA.SQLERRM)
    LET cancelacionSolicitudPortabilidadHTTPReq = NULL
    RETURN wsstatus
  END TRY
END FUNCTION


FUNCTION cancelacionSolicitudPortabilidadResponse_g()
  DEFINE wsstatus        INTEGER
  DEFINE nb              INTEGER
  DEFINE uri             STRING
  DEFINE setcookie       STRING
  DEFINE mustUnderstand  INTEGER
  DEFINE reader          xml.StaxReader

  LET wsstatus = -1

  LET uri = com.WebServiceEngine.GetOption("SoapModuleURI")
  #
  # CHECK PREVIOUS CALL  
  #
  IF cancelacionSolicitudPortabilidadHTTPReq IS NULL THEN
    # No request was sent
    CALL WSHelper_FillSOAP11WSError("Client","No request has been sent")
    RETURN -1
  END IF

  TRY
    #
    # PROCESS RESPONSE
    #
    IF cancelacionSolicitudPortabilidadHTTPResp IS NULL THEN
      # Still no response, try again
      LET cancelacionSolicitudPortabilidadHTTPResp = cancelacionSolicitudPortabilidadHTTPReq.getAsyncResponse()
    END IF

    IF cancelacionSolicitudPortabilidadHTTPResp IS NULL THEN
      # We got no response, still waiting for
      CALL WSHelper_FillSOAP11WSError("Client","Response was not yet received")
      RETURN -2
    END IF

      #
      # RETRIEVE SERVICE SESSION COOKIE
      #
      LET setcookie = cancelacionSolicitudPortabilidadHTTPResp.getHeader("Set-Cookie")
      IF setcookie IS NOT NULL THEN
        LET CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Cookie = WSHelper_ExtractServerCookie(setcookie,CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Address.Uri)
      END IF

      #
      # RETRIEVE HTTP RESPONSE Headers
      #
      CALL WSHelper_SetResponseHeaders(cancelacionSolicitudPortabilidadHTTPResp, CancelacionSolicitudPortabilidadService_CancelacionSolicitudPortabilidadServicePortTypeEndpoint.Binding.Response.Headers)
      CASE cancelacionSolicitudPortabilidadHTTPResp.getStatusCode()

        WHEN 500 # SOAP Fault
          #
          # STAX SOAP FAULT
          #
          LET reader = cancelacionSolicitudPortabilidadHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              CALL reader.nextTag()
            END IF
          ELSE
            IF WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL reader.nextSibling() # Skip SOAP headers
            END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11StartFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11FaultUntilDetail(reader) THEN
            EXIT CASE
          END IF
          IF WSHelper_CheckStaxSOAP11FaultDetail(reader) THEN
            #
            # STAX SOAP FAULT DESERIALIZE
            #
            CALL reader.nextSibling() # Skip SOAP detail
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndFault(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL cancelacionSolicitudPortabilidadHTTPResp.endXmlResponse(reader)

        WHEN 200 # SOAP Result
          #
          # STAX SOAP RESPONSE
          #
          LET reader = cancelacionSolicitudPortabilidadHTTPResp.beginXmlResponse() # Begin Streaming Response
          IF NOT WSHelper_ReadStaxSOAP11StartEnvelope(reader) THEN
            EXIT CASE
          END IF
          # Process SOAP headers 
          IF WSHelper_CheckStaxSOAP11Header(reader) AND NOT reader.isEmptyElement() THEN
            LET nb = 0
            CALL reader.nextTag()
            WHILE (reader.getEventType()=="START_ELEMENT")
              IF WSHelper_CheckStaxSOAP11HeaderActor(reader,uri) THEN
                LET mustUnderstand = WSHelper_GetStaxSOAP11HeaderMustUnderstand(reader)
                IF mustUnderstand = -1 THEN
                  CALL WSHelper_FillSOAP11WSError("Client","Invalid mustUnderstand value")
                  EXIT CASE
                END IF
                #
                # STAX SOAP RESPONSE HEADER DESERIALIZE
                #
                IF mustUnderstand THEN
                  CALL WSHelper_FillSOAP11WSError("MustUnderstand","Mandatory header block not understood")
                  EXIT CASE
                ELSE
                  CALL reader.nextSibling() # Skip header, not necessary
                END IF
              ELSE
                CALL reader.nextSibling() # Skip header, not intended to us
              END IF
            END WHILE
            IF NOT WSHelper_CheckStaxSOAP11Header(reader) THEN
              CALL WSHelper_FillSOAP11WSError("Client","No ending header tag found")
              EXIT CASE
            ELSE
              IF nb != 0 THEN
                CALL WSHelper_FillSOAP11WSError("Client","One or more headers are missing")
                EXIT CASE
              ELSE
                CALL reader.nextTag()
              END IF
            END IF
          ELSE
           IF reader.isEmptyElement() THEN
             CALL reader.nextTag()
           END IF
          END IF
          IF NOT WSHelper_ReadStaxSOAP11StartBody(reader) THEN
            EXIT CASE
          END IF
          # Retrieve SOAP Message taking soap:root attribute into account
          IF NOT WSHelper_RetrieveStaxSOAP11Message(reader) THEN
            EXIT CASE
          END IF
          #
          # STAX SOAP RESPONSE DESERIALIZE
          #
          CALL xml.Serializer.StaxToVariable(reader,solicitudCancelacionPortabilidadResponse)
          IF NOT WSHelper_ReadStaxSOAP11EndBody(reader) THEN
            EXIT CASE
          END IF
          IF NOT WSHelper_ReadStaxSOAP11EndEnvelope(reader) THEN
            EXIT CASE
          END IF
          # End Streaming Response
          CALL cancelacionSolicitudPortabilidadHTTPResp.endXmlResponse(reader)
          LET wsstatus = 0

        OTHERWISE
          CALL WSHelper_FillSOAP11WSError("Server","HTTP Error "||cancelacionSolicitudPortabilidadHTTPResp.getStatusCode()||" ("||cancelacionSolicitudPortabilidadHTTPResp.getStatusDescription()||")")

      END CASE
    CATCH
      LET wsstatus = status
      CALL WSHelper_FillSOAP11WSError("Server",SQLCA.SQLERRM)
    END TRY

  #
  # RESET VARIABLES
  #
  LET cancelacionSolicitudPortabilidadHTTPReq = NULL
  LET cancelacionSolicitudPortabilidadHTTPResp = NULL
  RETURN wsstatus

END FUNCTION


