####################################################################
#Modulo            =>AOP                                           #
#Programa          =>AOPC02.inc                                    #
#Objetivo          =>Archivo de definicion de datos                #
#Fecha inicio      =>17/08/2017                                    #
####################################################################

GLOBALS

   CONSTANT PROCESO                    		SMALLINT = 2501
   CONSTANT OPERACION                  		SMALLINT = 2
   CONSTANT IND_CONSULTA                 		SMALLINT = 1
   
END GLOBALS