####################################################################
#Modulo            =>AOP                                           #
#Programa          =>AOPL03.inc                                    #
#Objetivo          =>Archivo de definicion de datos                #
#Fecha inicio      =>10/08/2017                                    #
####################################################################

GLOBALS

   CONSTANT PROCESO                    		SMALLINT = 2501
   CONSTANT OPERACION                  		SMALLINT = 3
	CONSTANT MODULO                    			CHAR(3) = 'aop'



END GLOBALS