####################################################################
#Modulo            =>RET                                           #
#Programa          =>RETM01.inc                                    #
#Objetivo          =>Archivo de definicion de datos                #
#Fecha inicio      =>15 JULIO 2013                                 #
####################################################################
GLOBALS

   CONSTANT PROC_CUENTAS_CLABE         SMALLINT = 1522
   CONSTANT OP_VALIDA_ARCHIVO          SMALLINT = 1
   
END GLOBALS