####################################################################
#Modulo            =>SEP                                           #
#Programa          =>SEPWS02.inc                                   #
#Objetivo          =>Archivo de definicion de datos                #
#Fecha inicio      =>13 MAYO 2012                                  #
####################################################################

GLOBALS
END GLOBALS